TP_FINAL_ICT_106:main.c pile_avec_liste.c verification_expression.c verification_expression.h pile_avec_liste.h
	gcc -o dd main.c pile_avec_liste.c verification_expression.c
run:
	./dd
clean:
	rm dd
